apiVersion: v1
kind: Service
metadata:
  name: jeeves-weather-service
spec:
  selector:
    app: jeeves-weather
  ports:
  - protocol: "TCP"
    port: 6002
    targetPort: 5002
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeeves-weather
spec:
  selector:
    matchLabels:
      app: jeeves-weather
  replicas: 3
  template:
    metadata:
      labels:
        app: jeeves-weather
    spec:
      containers:
      - name: jeeves-weather
        image: jeeves-weather:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002