apiVersion: v1
kind: Service
metadata:
  name: jeeves-action-service
spec:
  selector:
    app: jeeves-action
  ports:
  - protocol: "TCP"
    port: 6004
    targetPort: 5004
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeeves-action
spec:
  selector:
    matchLabels:
      app: jeeves-action
  replicas: 3
  template:
    metadata:
      labels:
        app: jeeves-action
    spec:
      containers:
      - name: jeeves-action
        image: jeeves-action:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5004