apiVersion: v1
kind: Service
metadata:
  name: jeeves-database-service
spec:
  selector:
    app: jeeves-database
  ports:
  - protocol: "TCP"
    port: 6003
    targetPort: 5003
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeeves-database
spec:
  selector:
    matchLabels:
      app: jeeves-database
  replicas: 1
  template:
    metadata:
      labels:
        app: jeeves-database
    spec:
      containers:
      - name: jeeves-database
        image: jeeves-database:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5003