apiVersion: v1
kind: Service
metadata:
  name: jeeves-request-service
spec:
  selector:
    app: jeeves-request
  ports:
  - protocol: "TCP"
    port: 5005
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeeves-request
spec:
  selector:
    matchLabels:
      app: jeeves-request
  replicas: 3
  template:
    metadata:
      labels:
        app: jeeves-request
    spec:
      containers:
      - name: jeeves-request
        image: jeeves-request:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000